flowchart TD
    Start([Start])-->
    Name(Name)-->
    Age(Age)-->
    Address(Address)-->
    MyName("My name is + Name")-->
    MyAge("I'm + Age + years old")-->
    MyAddress("I live in + Address")-->
    End([END])
